### ISSUE TITLE
새 창에서 채팅 열기 후 댓글 작성 시 Prefix 추가

### ISSUE THREAD

**Issue by cksghks89** [cksghks89/SSAFix#10]
### 만들고자 하는 기능이 무엇인가요?
Youtube Live 채팅 박스 중 우측 메뉴 - 새 창에서 채팅 열기 후 열린 창에서도 Prefix 기능이 동작하도록 구현

 ### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
 1. 댓글 박스 태그 파악
 2. 이벤트 처리

 ### 예상 작업 시간
 1.5h

**Comment by gmzuddl** [comment]
### 댓글 박스 태그 파악 방법
- 새 창에서 새 탭 열기 : 태그 ID가 chatframe 을 찾을 수 없음
- chatframe의 null 유무에 따른 InputContainer 지정

### 새로운 ISSUE
-  setInterval 간격 내에 이벤트 Prefix생성 되지 않음
