### ISSUE TITLE
크롬 확장 프로그램 on/off 버튼 디자인

### ISSUE THREAD

**Issue by cksghks89** [cksghks89/SSAFix#6]
### 만들고자 하는 기능이 무엇인가요?
popup 창에서 프로그램을 on/off 할 수 있는 UI 디자인 변경

 ### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
 1. 적절한 버튼 선택 후 디자인 구현
 2. on/off 버튼 디자인

 ### 예상 작업 시간
 4h

**Comment by meoldae** [comment]
백준허브처럼 Pop Up에 토글 적용해보겠습니다!
