### ISSUE TITLE
입력값 초기화 버튼

### ISSUE THREAD

**Issue by cksghks89** [cksghks89/SSAFix#8]
### 만들고자 하는 기능이 무엇인가요?
초기화 버튼을 추가하여 입력된 prefix를 한 번에 지우는 기능 추가.

 ### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
 1. 버튼 디자인 및 이벤트 리스너 구현
 2. 크롬 storage 에서 미리 저장된 값이 있다면 삭제

 ### 예상 작업 시간
1.5h

**Comment by meoldae** [comment]
백준허브처럼 Pop Up에 토글 적용해보겠습니다!

**Comment by cksghks89** [comment]
동작 확인 후 merge 완료
#20
